services:
  # db:
  #   image: postgres
  #   container_name: db 
  #   restart: unless-stopped
  #   ports:
  #     - "${PGPORT:-5432}:5432"
  #   environment:
  #     POSTGRES_USER: ${PGUSER:-postgres}
  #     POSTGRES_PASSWORD: ${PGPASSWORD:-postgres}
  #     POSTGRES_DB: ${PGDB:-postgres}
  #   volumes:
  #     - ${POSTGRES_DATA:-./postgres_data}:/var/lib/postgresql/data:rw
  #     # - ./dbscripts:/docker-entrypoint-initdb.d

  db:
    image: mariadb:latest
    container_name: db
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"

  mkpipe:
    build:
      context: .
      dockerfile: Dockerfile
    # image: ghcr.io/mkpipe-etl/mkpipe:latest
    container_name: mkpipe
    depends_on:
      - db
    environment:
      - MKPIPE_PROJECT_DIR=/app
    volumes:
      - ./artifacts:/app/artifacts:rw
      - ./logs:/app/logs:rw
      - ./.env:/app/.env:ro
      - ./mkpipe_project.yaml:/app/mkpipe_project.yaml:ro
      - ./mkpipe-cron:/etc/cron.d/mkpipe-cron:rw  # Mount the crontab file for scheduling
    command: >
      sh -c "mkpipe run && crontab /etc/cron.d/mkpipe-cron && cron && tail -f /app/logs/mkpipe_log.log"
